/**
 * Cart screen styles — 2026 kit design language.
 *
 * Light end to end: editorial light header (the dark navy gradient is gone),
 * white cards with hairline borders + layered kit shadows, solid-ink
 * checkout CTA. All colour decisions come from @/shared/kit tokens.
 */
import { StyleSheet } from "react-native";
import { theme } from "@/shared/theme";
import { flexRow, isRtl, textAlignStart } from "@/utils/layout";
import { kit } from "@/shared/kit";

const IS_RTL = isRtl();
const TEXT_START = textAlignStart(IS_RTL);

export const s = StyleSheet.create({
  screen: {
    flex:            1,
    backgroundColor: kit.color.canvas,
  },

  // ── Header — light editorial ───────────────────────────────────────────────
  header: {
    paddingHorizontal: theme.spacing.lg,
    paddingBottom:     16,
    backgroundColor:   kit.color.canvas,
  },
  headerRow: {
    flexDirection:  flexRow(IS_RTL),
    alignItems:     "center",
    justifyContent: "space-between",
  },
  headerLeft: {
    flexDirection: flexRow(IS_RTL),
    alignItems:    "center",
    gap:           theme.spacing.md,
  },
  headerIcon: {
    width:           42,
    height:          42,
    borderRadius:    14,
    backgroundColor: kit.color.accentTint,
    alignItems:      "center",
    justifyContent:  "center",
  },
  headerEyebrow: {
    fontFamily: theme.fonts.bold,
    fontSize: 10, lineHeight: 15,
    color: kit.color.inkFaint,
    textAlign: TEXT_START,
    includeFontPadding: false,
  },
  headerTitle: {
    fontFamily: theme.fonts.black,
    fontSize: 24, lineHeight: 33,
    color: kit.color.ink,
    textAlign: TEXT_START,
    includeFontPadding: false,
  },
  headerActions: {
    flexDirection: flexRow(IS_RTL),
    alignItems:    "center",
    gap:           10,
  },
  countBadge: {
    backgroundColor:   kit.color.accentTint,
    borderRadius:      kit.radius.pill,
    paddingHorizontal: 11,
    paddingVertical:   6,
  },
  countText: {
    fontFamily: theme.fonts.bold,
    fontSize: 11, lineHeight: 16,
    color: kit.color.accentDeep,
    includeFontPadding: false,
  },
  clearBtn: {
    flexDirection:     flexRow(IS_RTL),
    alignItems:        "center",
    gap:               5,
    paddingHorizontal: 12,
    height:            34,
    borderRadius:      kit.radius.pill,
    backgroundColor:   kit.color.dangerTint,
  },
  clearText: {
    fontFamily: theme.fonts.bold,
    fontSize: 11, lineHeight: 16,
    color: kit.color.danger,
    includeFontPadding: false,
  },

  // ── List header components ─────────────────────────────────────────────────
  warnBanner: {
    flexDirection:     flexRow(IS_RTL),
    alignItems:        "center",
    gap:               10,
    backgroundColor:   kit.color.warnTint,
    borderRadius:      kit.radius.control,
    paddingHorizontal: 14,
    paddingVertical:   11,
    marginBottom:      theme.spacing.xs,
  },
  warnText: {
    flex:       1,
    fontFamily: theme.fonts.semibold,
    fontSize: 12, lineHeight: 18,
    color: kit.color.warn,
    textAlign: TEXT_START,
    includeFontPadding: false,
  },
  branchPill: {
    flexDirection:     flexRow(IS_RTL),
    alignItems:        "center",
    gap:               theme.spacing.md,
    backgroundColor:   kit.color.surface,
    borderRadius:      kit.radius.card,
    paddingHorizontal: 14,
    paddingVertical:   theme.spacing.md,
    marginBottom:      theme.spacing.xs,
    borderWidth:       1,
    borderColor:       kit.color.line,
    ...kit.shadow.raised,
  },
  branchIconBox: {
    width:           34,
    height:          34,
    borderRadius:    11,
    backgroundColor: kit.color.accentTint,
    alignItems:      "center",
    justifyContent:  "center",
  },
  branchEyebrow: {
    fontFamily: theme.fonts.regular,
    fontSize: 10, lineHeight: 15,
    color: kit.color.inkFaint,
    textAlign: TEXT_START,
    includeFontPadding: false,
  },
  branchName: {
    fontFamily: theme.fonts.black,
    fontSize: 13, lineHeight: 19,
    color: kit.color.ink,
    textAlign: TEXT_START,
    marginTop: 1,
    includeFontPadding: false,
  },
  deliveryCard: {
    backgroundColor: kit.color.surface,
    borderRadius:    kit.radius.card,
    padding:         theme.spacing.lg,
    marginBottom:    theme.spacing.xs,
    borderWidth:     1,
    borderColor:     kit.color.line,
    ...kit.shadow.raised,
  },
  freeRow: {
    flexDirection: flexRow(IS_RTL),
    alignItems:    "center",
    gap:           14,
  },
  freeIconBox: {
    width:           42,
    height:          42,
    borderRadius:    14,
    alignItems:      "center",
    justifyContent:  "center",
    backgroundColor: kit.color.success,
  },
  freeTitle: {
    fontFamily: theme.fonts.black,
    fontSize: 15, lineHeight: 22,
    color: kit.color.success,
    textAlign: TEXT_START,
    includeFontPadding: false,
  },
  freeSub: {
    fontFamily: theme.fonts.regular,
    fontSize: 11, lineHeight: 17,
    color: kit.color.inkSoft,
    textAlign: TEXT_START,
    marginTop: 2,
    includeFontPadding: false,
  },
  progressHeader: {
    flexDirection:  flexRow(IS_RTL),
    alignItems:     "center",
    justifyContent: "space-between",
    marginBottom:   10,
  },
  progressLeft: {
    flexDirection: flexRow(IS_RTL),
    alignItems:    "center",
    gap:           7,
    flex:          1,
  },
  progressLabel: {
    fontFamily: theme.fonts.semibold,
    fontSize: 12, lineHeight: 18,
    color: kit.color.inkSoft,
    textAlign: TEXT_START,
    flex: 1,
    includeFontPadding: false,
  },
  progressPct: {
    fontFamily: theme.fonts.black,
    fontSize: 13, lineHeight: 19,
    color: kit.color.ink,
    marginStart: theme.spacing.sm,
    includeFontPadding: false,
  },
  track: {
    height:          7,
    backgroundColor: kit.color.well,
    borderRadius:    4,
    overflow:        "hidden",
  },
  fill: {
    height:          "100%",
    backgroundColor: kit.color.accent,
    borderRadius:    4,
  },
  trustRow: {
    flexDirection:     flexRow(IS_RTL),
    backgroundColor:   kit.color.surface,
    borderRadius:      kit.radius.card,
    paddingVertical:   14,
    paddingHorizontal: theme.spacing.xs,
    marginBottom:      theme.spacing.xs,
    borderWidth:       1,
    borderColor:       kit.color.line,
    ...kit.shadow.raised,
  },
  trustCell: {
    flex:              1,
    alignItems:        "center",
    gap:               6,
    paddingHorizontal: theme.spacing.xs,
  },
  trustDivider: {
    borderEndWidth: StyleSheet.hairlineWidth,
    borderEndColor: kit.color.lineStrong,
  },
  trustIconBox: {
    width:          30,
    height:         30,
    borderRadius:   10,
    alignItems:     "center",
    justifyContent: "center",
  },
  trustLabel: {
    fontFamily: theme.fonts.bold,
    fontSize: 9, lineHeight: 13,
    color: kit.color.inkSoft,
    textAlign: "center",
    includeFontPadding: false,
  },

  // ── Cart item card ──────────────────────────────────────────────────────────
  card: {
    backgroundColor:   kit.color.surface,
    borderRadius:      kit.radius.card,
    paddingHorizontal: 14,
    paddingTop:        theme.spacing.md,
    paddingBottom:     14,
    gap:               10,
    borderWidth:       1,
    borderColor:       kit.color.line,
    ...kit.shadow.raised,
  },
  cardTopRow: {
    flexDirection:  flexRow(IS_RTL),
    alignItems:     "center",
    justifyContent: "space-between",
  },
  catLabel: {
    fontFamily: theme.fonts.bold,
    fontSize: 10, lineHeight: 15,
    color: kit.color.inkFaint,
    textAlign: TEXT_START,
    includeFontPadding: false,
  },
  deleteBtn: {
    width:           30,
    height:          30,
    borderRadius:    15,
    backgroundColor: kit.color.dangerTint,
    alignItems:      "center",
    justifyContent:  "center",
  },
  cardMidRow: {
    flexDirection: flexRow(IS_RTL),
    alignItems:    "flex-start",
    gap:           theme.spacing.md,
  },
  imgBox: {
    width:           72,
    height:          72,
    borderRadius:    kit.radius.control,
    overflow:        "hidden",
    backgroundColor: kit.color.well,
    flexShrink:      0,
  },
  imgFallback: {
    flex:           1,
    alignItems:     "center",
    justifyContent: "center",
  },
  productName: {
    flex:       1,
    fontFamily: theme.fonts.black,
    fontSize: 14, lineHeight: 21,
    color: kit.color.ink,
    textAlign: TEXT_START,
    includeFontPadding: false,
  },
  cardBottomRow: {
    flexDirection:  flexRow(IS_RTL),
    alignItems:     "center",
    justifyContent: "space-between",
    marginTop:      2,
  },
  priceWrap: {
    flexDirection: flexRow(IS_RTL),
    alignItems:    "baseline",
    gap:           theme.spacing.xs,
  },
  lineTotal: {
    fontFamily: theme.fonts.black,
    fontSize: 18, lineHeight: 26,
    color: kit.color.ink,
    includeFontPadding: false,
  },
  currency: {
    fontFamily: theme.fonts.bold,
    fontSize: 11, lineHeight: 16,
    color: kit.color.inkSoft,
    includeFontPadding: false,
  },
  unitHint: {
    fontFamily: theme.fonts.regular,
    fontSize: 10, lineHeight: 15,
    color: kit.color.inkFaint,
    marginStart: theme.spacing.xs,
    includeFontPadding: false,
  },
  // ── Pill stepper — circle buttons inside a pill container ─────────────────
  stepper: {
    flexDirection:   "row",
    alignItems:      "center",
    gap:             4,
    backgroundColor: kit.color.well,
    borderRadius:    kit.radius.pill,
    padding:         4,
  },
  stepBtn: {
    width:           32,
    height:          32,
    borderRadius:    16,
    backgroundColor: kit.color.surface,
    alignItems:      "center",
    justifyContent:  "center",
    ...kit.shadow.raised,
  },
  stepBtnDisabled: {
    backgroundColor: kit.color.well,
    shadowOpacity:   0,
    elevation:       0,
  },
  qtyNum: {
    fontFamily: theme.fonts.black,
    fontSize: 15, lineHeight: 22,
    color: kit.color.ink,
    minWidth: 22,
    textAlign: "center",
    includeFontPadding: false,
  },
  qtyNumMax: {
    color: kit.color.warn,
  },
  maxHint: {
    flexDirection:     flexRow(IS_RTL),
    alignItems:        "center",
    gap:               theme.spacing.xs,
    alignSelf:         "flex-start",
    paddingHorizontal: theme.spacing.sm,
    paddingVertical:   4,
    backgroundColor:   kit.color.warnTint,
    borderRadius:      kit.radius.pill,
  },
  maxHintText: {
    fontFamily: theme.fonts.bold,
    fontSize: 10, lineHeight: 15,
    color: kit.color.warn,
    includeFontPadding: false,
  },

  // ── Checkout Footer — sticky, elevated, horizontal layout ──────────────────
  footer: {
    backgroundColor:   kit.color.surface,
    paddingHorizontal: theme.layout.pagePaddingH,
    paddingTop:        16,
    borderTopWidth:    StyleSheet.hairlineWidth,
    borderTopColor:    kit.color.line,
    shadowColor:       "#0A1220",
    shadowOffset:      { width: 0, height: -6 },
    shadowOpacity:     0.06,
    shadowRadius:      16,
    elevation:         14,
  },
  footerHandle: {
    width:           36,
    height:          3,
    borderRadius:    2,
    backgroundColor: kit.color.lineStrong,
    alignSelf:       "center",
    marginBottom:    14,
  },
  totalsBlock: {
    gap:               5,
    marginBottom:      12,
    paddingBottom:     10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: kit.color.line,
  },
  totalRow: {
    flexDirection:  flexRow(IS_RTL),
    alignItems:     "center",
    justifyContent: "space-between",
  },
  totalLabel: {
    fontFamily: theme.fonts.regular,
    fontSize: 12, lineHeight: 18,
    color: kit.color.inkFaint,
    includeFontPadding: false,
  },
  totalValue: {
    fontFamily: theme.fonts.semibold,
    fontSize: 12, lineHeight: 18,
    color: kit.color.inkSoft,
    includeFontPadding: false,
  },
  totalFree: {
    fontFamily: theme.fonts.black,
    fontSize: 12, lineHeight: 18,
    color: kit.color.success,
    includeFontPadding: false,
  },
  // ── Checkout row — price + solid-ink pill CTA ──────────────────────────────
  checkoutRow: {
    flexDirection:  "row",     // RTL system flips: price→right, btn→left
    alignItems:     "center",
    justifyContent: "space-between",
    gap:            14,
  },
  priceBlock: { gap: 2 },
  priceLabel: {
    fontFamily: theme.fonts.regular,
    fontSize: 11, lineHeight: 16,
    color: kit.color.inkFaint,
    textAlign: TEXT_START,
    includeFontPadding: false,
  },
  priceRow: {
    flexDirection: "row",   // RTL auto-mirrors: currency right of number
    alignItems:    "baseline",
    gap:           4,
  },
  priceTotal: {
    fontFamily: theme.fonts.black,
    fontSize: 26, lineHeight: 34,
    color: kit.color.ink,
    includeFontPadding: false,
  },
  priceCurrency: {
    fontFamily: theme.fonts.bold,
    fontSize: 13, lineHeight: 19,
    color: kit.color.inkSoft,
    includeFontPadding: false,
  },
  checkoutOuter: {
    flex:         1,
    borderRadius: kit.radius.pill,
    overflow:     "hidden",
    maxWidth:     220,
  },
  checkoutInner: {
    flexDirection:     flexRow(IS_RTL),
    alignItems:        "center",
    justifyContent:    "center",
    gap:               8,
    paddingVertical:   16,
    paddingHorizontal: 20,
    borderRadius:      kit.radius.pill,
    backgroundColor:   kit.color.ink,
  },
  checkoutInnerDisabled: {
    backgroundColor: kit.color.inkFaint,
  },
  checkoutText: {
    fontFamily: theme.fonts.black,
    fontSize: 14, lineHeight: 20,
    color: kit.color.onInk,
    includeFontPadding: false,
  },
});
